### ISSUE TITLE
Make the menu text shorter

### ISSUE THREAD

**Issue by pravic** [tomzorz/PasteHere#1]
It enormously stretches the context menu.

**Comment by tomzorz** [comment]
You can edit [the 4th line](https://github.com/tomzorz/PasteHere/blob/master/sources/reg%20file/pastehere.reg#L4) in the regedit file, and re-run it - changing the text to whatever you want

**Comment by tomzorz** [comment]
Closed as there's a workaround.

**Comment by tomzorz** [comment]
v2 uses the shorter "Paste clipboard as file" out of the box: https://github.com/tomzorz/PasteHere/releases/tag/v2
